export const RouteInformation = {
  homePage: '/',
  authPage: '/auth',
  loginPage: '/auth/login',
  unauthorizedPage: '/auth/unauthorized',
  notFoundPage: '/auth/not-found',
  eventsPage: '/app/events',
  eventPage: '/app/events/event',
  askEventPage: '/app/ask',
  collectionsPage: '/app/collections',
  collectionPage: '/app/collections/collection',
  usersPage: '/app/users',
  userPage: '/app/users/user',
  borrowsPage: '/app/borrow',
  borrowPage: '/app/borrow/borrow',
  profilePage: '/app/profile',
};
