export const RouteInformation = {
  homePage: '/',
  authPage: '/auth',
  loginPage: '/auth/login',
  unauthorizedPage: '/auth/unauthorized',
  notFoundPage: '/auth/not-found',
  eventsPage: '/events',
  eventPage: '/events/event',
  askEventPage: '/ask',
  collectionsPage: '/collections',
  collectionPage: '/collections/collection',
  usersPage: '/users',
  userPage: '/users/user',
  borrowsPage: '/borrow',
  borrowPage: '/borrow/borrow',
  profilePage: '/profile',
};
